# Generated by Django 5.0.2 on 2024-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0002_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='', null=True, upload_to='song_covers'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_file',
            field=models.FileField(default='', null=True, upload_to='songs'),
        ),
    ]
