# Generated by Django 5.0.2 on 2024-03-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0004_album_playlist_user_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
